version: '3.8'
services:
  app:
    container_name: nextjs-app
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - NODE_ENV=development
    command: yarn dev

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
