# Generated by Django 5.1.5 on 2025-07-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedbacksubmission_alter_services_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='description',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='items',
        ),
        migrations.RemoveField(
            model_name='services',
            name='title',
        ),
        migrations.RemoveField(
            model_name='works',
            name='description',
        ),
        migrations.RemoveField(
            model_name='works',
            name='title',
        ),
        migrations.AddField(
            model_name='questions',
            name='description_en',
            field=models.CharField(default='', max_length=50, verbose_name='Описание (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='description_ru',
            field=models.CharField(default='', max_length=50, verbose_name='Описание (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='title_en',
            field=models.CharField(default='', max_length=50, verbose_name='Заголовок (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='title_ru',
            field=models.CharField(default='', max_length=50, verbose_name='Заголовок (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='items_en',
            field=models.JSONField(default=list, verbose_name='Пункты (EN)'),
        ),
        migrations.AddField(
            model_name='services',
            name='items_ru',
            field=models.JSONField(default=list, verbose_name='Пункты (RU)'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(default='', max_length=50, verbose_name='Заголовок (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='title_ru',
            field=models.CharField(default='', max_length=50, verbose_name='Заголовок (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='description_en',
            field=models.CharField(default='', max_length=50, verbose_name='Описание (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='description_ru',
            field=models.CharField(default='', max_length=50, verbose_name='Описание (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='title_en',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='title_ru',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок (RU)'),
            preserve_default=False,
        ),
    ]
