# Generated by Django 5.1.5 on 2025-07-15 05:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_questions_description_remove_questions_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/works/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Фото работы')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.works')),
            ],
        ),
    ]
